name: 'SSAS Run Script'
description: 'This actions is made to run scripts on SSAS instances on Azure'
author: Me :D
branding:
  icon: 'database'  
  color: 'orange'
inputs:
  scripts:
    description: 'Ordered list of scripts to execute'
    required: true
  analysisInstance:
    description: 'Full name of the Analysis Service Instance'
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/script.ps1
      shell: pwsh
